package dev.optimal.tracker.designsystem.theme

import androidx.compose.ui.graphics.Color

val BlazeOrange        = Color(0xFFFF5722)
val BlazeOrangeLight   = Color(0xFFFF8A65)
val BlazeOrangeDark    = Color(0xFFBF360C)
val ElectricCyan       = Color(0xFF00E5FF)
val ElectricCyanLight  = Color(0xFF6EFFFF)
val ElectricCyanDark   = Color(0xFF00B2CC)
val PowerLime          = Color(0xFFCCFF90)
val PowerLimeDark      = Color(0xFF76FF03)
val BackgroundDark     = Color(0xFF0D0D0D)
val SurfaceDark        = Color(0xFF1A1A1A)
val SurfaceVariant     = Color(0xFF242424)
val SurfaceContainer   = Color(0xFF2C2C2C)
val OnPrimary          = Color(0xFFFFFFFF)
val OnSecondary        = Color(0xFF003340)
val OnBackground       = Color(0xFFF2F2F2)
val OnSurface          = Color(0xFFE8E8E8)
val OnSurfaceVariant   = Color(0xFFB0B0B0)
val OutlineDark        = Color(0xFF3A3A3A)
val OutlineVariant     = Color(0xFF2E2E2E)
val Success            = Color(0xFF69F0AE)
val Warning            = Color(0xFFFFD740)
val Error              = Color(0xFFFF5252)
val OnError            = Color(0xFF690000)
